version: 0.2

phases:
 install:
    runtime-versions:
      golang: 1.12
    commands:
      - sudo nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
 build:
    commands:
       - cd src 
       - go get -v -t ./ 
       - apt-get update 
       - apt-get -y install nodejs 
       - npm install -g @angular/cli 
       - cd ui && npm install
       - apt-get install -y chromium-browser 
       - cd .. && make integration
       - service docker start
       - cd .. && docker build -t planningpoker .
       - docker save -o planningpoker.tar planningpoker
       
artifacts:
  files:
    - '**/*'       
