name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 1
        path: /home/runner/go/src/github.com/magetron/planning-poker-go/
    - name: Go Makefile, go!
      if: success()
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        cd $GOPATH/src/github.com/magetron/planning-poker-go/src
        go install
        go build
        make test
