name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - name: setup env
      run: |
        env

    - name: Go Makefile, go!
      if: success()
      run: |
        cd src
        go install    
        go build
        make test
