name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: actions/setup-go@v1
      with:
        go-version: 1.x
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 1
    - name: Go Makefile, go!
      if: success()
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        export GOPATH=`go env GOPATH`
        mkdir -p $GOPATH/src/github.com/magetron/planning-poker-go/
        mv /home/runner/work/planning-poker-go/planning-poker-go/src $GOPATH/src/github.com/magetron/planning-poker-go/
        cd $GOPATH/src/github.com/magetron/planning-poker-go
        go install
        go build
        make test
